name: Code Quality

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check code quality
        id: check
        continue-on-error: true
        run: npm run check

      - name: Run tests (if available)
        id: test
        continue-on-error: true
        run: npm run test || echo "No tests configured yet"

      - name: Auto-fix issues
        if: steps.check.outcome == 'failure'
        run: npm run check:write

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request with fixes
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: auto-fix formatting and linting issues'
          title: '🤖 Auto-fix: Code Quality'
          body: |
            ## Automated Code Quality Fixes

            This PR was automatically generated to fix formatting and linting issues detected on main branch.

            ### Changes:
            - Auto-formatted code with Biome
            - Auto-fixed linting violations where possible

            **Workflow run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **Commit:** ${{ github.sha }}

            Please review and merge if the fixes look correct.
          branch: auto-fix/code-quality-${{ github.run_number }}
          delete-branch: true
          labels: |
            automated
            code-quality

      - name: Create issue for unfixable problems
        if: |
          steps.git-check.outputs.changes != 'true' &&
          (steps.check.outcome == 'failure' || steps.test.outcome == 'failure')
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🚨 Code Quality Issues Detected (Auto-fix failed)';
            const body = `## Code Quality Check Failed

            Automated code quality checks failed and could not be automatically fixed.

            ### Failed Checks:
            ${'${{ steps.check.outcome }}' === 'failure' ? '- ✗ Biome check (formatting/linting)' : '- ✓ Biome check'}
            ${'${{ steps.test.outcome }}' === 'failure' ? '- ✗ Tests' : '- ✓ Tests'}

            ### Details:
            **Workflow run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **Commit:** ${{ github.sha }}
            **Branch:** ${{ github.ref_name }}

            ### Next Steps:
            1. Review the workflow logs linked above to see specific errors
            2. Fix the issues manually in a new branch
            3. Create a PR with the fixes

            These issues require manual review and cannot be auto-fixed by Biome.
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['automated', 'code-quality']
            });
